### ISSUE TITLE
Error in Plexus.csv

### ISSUE THREAD

**Issue by 4n0nym0u53** [techlore/plexus#162]
There's an error in Plexus.csv, which appears to originate from commit `b78e3759566fd47cad3b3159d4907d025f33f87c`. Specifically, line 269 has 9 rows instead of 7:
```
Google Maps,April,2021,2,Cannot add Google account,2,"Cannot open if logged in, works if not logged in",4,No reported issues
```
I suppose this could be corrected by removing the middle rating, as it seems to be an old rating. Then it would look like this:
```
Google Maps,April,2021,2,Cannot add Google account,4,No reported issues
```

**Comment by tomkonidas** [comment]
Thanks for the fix @4n0nym0u53 !
