### ISSUE TITLE
App search page and individual app pages show different scores

### ISSUE THREAD

**Issue by nikitaindik** [techlore/plexus#200]
Take 9GAG, for example.
On the search page scores are X - 4:
<img width="392" alt="Screenshot 2021-07-15 at 11 27 11" src="https://user-images.githubusercontent.com/15949146/125764945-e585ab76-5423-4311-9011-79ccefc8d728.png">

But when you open the app page at https://plexus.techlore.tech/applications/9gag it shows X - 3:
<img width="748" alt="Screenshot 2021-07-15 at 11 27 44" src="https://user-images.githubusercontent.com/15949146/125764955-bd8a2318-b39e-44d1-a8c8-5be89242575e.png">

Looks like it's caused by the fact that the search page and app page use different JSONs with different data.
Search page uses: https://plexus.techlore.tech/page-data/sq/d/485815842.json
App page uses: https://plexus.techlore.tech/page-data/applications/9gag/page-data.json

There are multiple apps that behave like this. 

Some app pages don't work at all. For example https://plexus.techlore.tech/applications/kate-mobile returns a 404.

I tried pulling the repo and building locally - everything works fine.

Rebuilding and redeploying the app should probably fix both issues.

**Comment by tomkonidas** [comment]
I believe this is an issue with Netlify's cache, 
I had an experimental feature turned on to not rebuild the whole site and only the differences.

Thanks @nikitaindik for raising the issue! It is now resolved

Please see https://github.com/techlore/plexus/commit/faef7028585cd75403ac4d4fb888ec4dd1ab5842 for more details
