### ISSUE TITLE
Add new sandboxed play services on GrapheneOS

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [techlore/plexus#211]
Hi all,

Please add support for the new sandboxed play services on GrapheneOS in addition to the two options "microg" and "de-googled". See: https://grapheneos.org/usage#sandboxed-play-services

Best regards,
PhysicsIsAwesome

**Comment by techlore-official** [comment]
Exciting news indeed! Will definitely be wanting to incorporate this.

Some context, the shitty Plexus CSV format is on its way out shortly and Plexus will be running on a proper system. I want to implement a proper system before adding more data fields to the current chart. The gOS sandboxed play services are currently experimental, which should hopefully give us enough time to integrate things properly before the gates are fully opened on their end. 

Going to keep the issue open and keep it updated as progress is made on our ends.

**Comment by jbmagination** [comment]
I am really hoping it's gonna be in JSON instead of CSV. Please be in JSON 🙏

**Comment by henryistaken** [comment]
Hey everyone! Couple updates:
1) First, very happy to report JSON is here: https://github.com/techlore/Plexus-app The application is completed and we'll be starting the transition of moving the entire contribution workflow over there. So we hope you all enjoy that once it's said & done!
2) After talking it through, we actually don't think sandboxed play services are necessary for Plexus. It seems that the sandboxed play services function almost exactly the same as normal Play Services, so we think it's safe to assume things will work as normal. We're going to keep Plexus with a focus on either no Google Play services, or alternatives (like MicroG)
