### ISSUE TITLE
Multi entries?

### ISSUE THREAD

**Issue by AngryLasagna** [techlore/plexus#23]
I've got a bunch of phones.
Should I upload entries for all environments?
I've got some Graphene, Lineage without Gapps, Lineagemicrog, Pixel, Oneplus, Huawei, Garbage1-5 ....

**Comment by PrestoSole** [comment]
Hi, It should be better to do so

**Comment by techlore-official** [comment]
As of right now, the only two environments we’re evaluating are fully de-googled (with no Google Play Services alternatives) and MicroG. Down the road we can get more specific to include OS version, app version, ROM, and even settings. But one step at a time

**Comment by techlore-official** [comment]
Closing this issue as it’s addressed in our future goals in the readme. Thanks for sending over the idea!
