### ISSUE TITLE
Specify whether cloud messaging is on or off for microG

### ISSUE THREAD

**Issue by chaptergy** [techlore/plexus#24]
Whether notifications work with microG is usually dependent on whether Google Cloud Messaging has been switched on. Maybe this info would be useful in the notes, in case some notifications don't work even with gcm.

**Comment by PrestoSole** [comment]
Hi, do u mean do add this message in the README.md file?

**Comment by techlore-official** [comment]
Good suggestion, will see about incorporating this down the road

**Comment by techlore-official** [comment]
Have now added this to the Testing Standards in the readme. https://github.com/techlore/plexus/commit/ae5138fa94b0360851eda4d320d699e161657a72
