### ISSUE TITLE
How to Deal with Apps that are Censored on Google Play but Full Version Available from Developer?

### ISSUE THREAD

**Issue by CPete88** [techlore/plexus#240]
I have also seen some developers that offer censored versions of their app in the original Google Play Store and an unrestricted version directly from their website (for example, Minds the social media platform). Should we list these in the CSV?

Pros:
- Makes it easier for new de-Googled Android users to find which apps are now available as a direct download (no Google Play dependencies)
- Helps developers trying to get away from the Google Play Store find users
- Encourages developers to not depend on Google Play even if their apps are proprietary (not open-sourced and not available on F-Droid for example).

Cons:
- This adds another column to track (i.e. URL for the direct download website)
- We would need to adjust the project's app listing policy. We currently do not list F-Droid apps with the expectation that users can browser there for apps without Google Play dependencies.

**Comment by Neyl-123** [comment]
I think it's a good idea to include them, for example snaptube is banned from Google Play but can be downloaded on their website (https://www.snaptubeapp.com/)

**Comment by henry-fisher** [comment]
The new Plexus app includes the source of installation now within the application to solve this issue! Hope that helps!
