### ISSUE TITLE
Permission to clean up CSV file & fix misformatted comment strings?

### ISSUE THREAD

**Issue by JoshuaKimsey** [techlore/plexus#270]
I noticed recently while adding my own additions to the CSV file for the #268 pull request that the CSV file appears to render rather messily when opening in something like a spreadsheet program. The reason for this is that people have left comments with commas in them without quotation marks closing off their comment string. 

I wanted to ask permission to go through and clean up the CSV file to make it easier to open with a normal spreadsheet program, instead of having to do it in a plain text editor like I did. Also wanted to ask if the instructions for how to make a contribution can be updated to reflect the need to close off comments with quotation marks to prevent this issue from happening again.

**Comment by UnixPhonez** [comment]
Add issue #271 to the CSV to cause I don't wanna mess up anything.
