### ISSUE TITLE
`Plexus.csv` file links not working

### ISSUE THREAD

**Issue by auroraanna** [techlore/plexus#322]
The links in the readme to the `Plexus.csv` file are not working. Where is the template file? How can contribute without emailing?

**Comment by henryistaken** [comment]
<img width="789" alt="Screenshot 2023-04-04 at 1 46 21 PM" src="https://user-images.githubusercontent.com/64515030/229916744-782bef37-7db1-4d61-8bb3-b19f48f63240.png">
Just part of the transition that you'll see in the readme. This will all be resolved soon
