### ISSUE TITLE
Submissions for lots of closed source apps

### ISSUE THREAD

**Issue by secretmango** [techlore/plexus#325]
GrapheneOS Android 13, no sandboxed Play services or microg, no root

Comdirect Phototan working normally, no push notifications

Comdirect app working normally

SecureGo plus app working, no push notifications

GLS Banking not working without push notifications

GLS mBank working

Spotify working

ebay kleinanzeigen working, no push, no maps

ToxFox: working normally

Peta veganstart: working normally

acr phone: working normally

Cwtch: working normally

foodsharing: working normally

foxit pdf reader: normally (internet off recommended)

xodo pdf: normally (internet off recommended)

snapseed: working normally (internet off recommended)

Google camera: requires [google camera services](https://f-droid.org/en/packages/de.lukaspieper.gcam.services), works perfectly then (internet off recommended)

viral icon pack: working normally (internet off recommended)

**Comment by zimral-github** [comment]
update: former "ebay-kleinanzeigen" is now "Kleinanzeigen" (the company has been sold) and it is not working anymore. The app is crashing. No further research done. Details: OS = CalyxOS including microG.

**Comment by xdubx** [comment]
Current CalyxOs with microG and "Kleinanzeigen" works for me.

satellite.me works in the meantime.

**Comment by firefoxlover** [comment]
crazy, for me it worked normally afaik, but I now use the webapp, which sucks though.

Grapheneos latest, no google at all

**Comment by zimral-github** [comment]
Pixel5, CalyxOS v4.13.2, MicroG v0.2.28.233013-125 provided with this build, device profile Auto: Native, Safetynet: off.  No further mods, just a standard installation. Starting "Kleinanzeigen" shows their logo for some seconds, then it diasappers without further error message. Access to notifications, camera, etc has been given. I didn't use "Kleinanzeigen"  for some time but as far as i remember, the problem started with the MicroG upstream changes in Calyx v4.12.2 in early september. My Pixel4a running CalyxOS 4.13.3, same MicroG setup using version 0.2.29.233013-49 is showing exact the same behavior.

**Comment by henry-fisher** [comment]
We have now migrated to the application, so there's no need to manually submit data here. :) We would still love to have your experiences submitted from the Plexus app—it's a lot more convenient for everyone!

**Comment by secretmango** [comment]
actually, seeing your ignorance towards GrapheneOS, I am not sure if I want to invest any more time in this.

sorry!
