### ISSUE TITLE
Remove Matrix link/icon

### ISSUE THREAD

**Issue by jonaharagon** [techlore/plexus#340]
I'm confused about where the source code for this website actually is, because I can't find it in this repo. Anyways, I think the Matrix icon in the footer should be replaced with this code:

```
<a href="https://discuss.techlore.tech/c/techlore/plexus/12" class="ml-3 md:ml-5 text-gray-100 hover:text-gray-200" rel="noopener" target="_blank">
  <span class="sr-only">Discussion Forum</span>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="w-auto h-6" fill="currentColor"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M225.9 32C103.3 32 0 130.5 0 252.1 0 256 .1 480 .1 480l225.8-.2c122.7 0 222.1-102.3 222.1-223.9C448 134.3 348.6 32 225.9 32zM224 384c-19.4 0-37.9-4.3-54.4-12.1L88.5 392l22.9-75c-9.8-18.1-15.4-38.9-15.4-61 0-70.7 57.3-128 128-128s128 57.3 128 128-57.3 128-128 128z"></path></svg>
</a>
```

And the Matrix icon in the header should just be removed.

<img width="231" alt="EaVLv2RalyuuoG6p" src="https://github.com/techlore/plexus/assets/3637842/0b46c267-e145-4969-baa8-4d58963abd70">

👍

**Comment by tomkonidas** [comment]
Hey @jonaharagon, we are in the middle of rebuilding the whole project so the live site does not reflect the codebase. We paused the deploys until we will be ready for the new launch.

I did not re-create the frontend web app yet (only the backend API for the mobile application). But when I do I will use the snippet you provided. 🙏

**Comment by jonaharagon** [comment]
@tomkonidas where is the live site actually hosted at the moment?

**Comment by tomkonidas** [comment]
> @tomkonidas where is the live site actually hosted at the moment?

The new site is at https://plexus.fly.dev. Once we are ready, we will update our DNS to point to this new server.

**Comment by henry-fisher** [comment]
Should be fixed now with the new site!
