### ISSUE TITLE
Santander UK is listed as working, but it does not work (with MicroG)

### ISSUE THREAD

**Issue by againstpetra** [techlore/plexus#354]
It's listed as all green: https://plexus.techlore.tech/applications/santander-uk

But for me, when I log in, I get redirected to an "access denied" page - it's completely unusable.

**Comment by henry-fisher** [comment]
We have now migrated to the application, so there's no need to manually submit data here. :) We would still love to have your experiences submitted from the Plexus app—it's a lot more convenient for everyone!
