### ISSUE TITLE
What is the current status of the refactoring? ("Important updates as of May 12, 2022") 

### ISSUE THREAD

**Issue by rugk** [techlore/plexus#355]
I came here to contribute an app update and read "Important updates as of May 12, 2022" in the Readme. The TL;DR/what I take away is: do not contribute yet, you will have a way to submit it via app/website soon.

The thing just is, this update is two years old and I see no issue where progress is being reported. At the same time there are apparently PRs to update the old csv.

So what should I do? And what is the current status of that refactoring or how I'd call it?

**Comment by rugk** [comment]
Thanks. Though I already see a "competition project": https://github.com/jonathanklee/Sapio/issues/24

**Comment by henry-fisher** [comment]
The app is now live :) And I left a comment on the Sapio project if they ever want to work together. It's awesome to see a similar project!
