### ISSUE TITLE
[Issue]: GrapheneOS doesn't count? 

### ISSUE THREAD

**Issue by rumpelstilz69** [techlore/plexus#358]
### Description

doesn't work with degoogled Grapheneos! ?

### Steps to reproduce the issue

Try to rate

### Error messages/logs

Your Device must be degoogled or have microg

### Terms

- [X] This is not a duplicate of another issue.

**Comment by henry-fisher** [comment]
![image](https://github.com/user-attachments/assets/d244e81e-02fe-4d2f-ba78-bd1e19e9f3bb)
![image](https://github.com/user-attachments/assets/5b08f5a6-d2a4-43d6-b6e2-65bf4ebd9b1b)
![image](https://github.com/user-attachments/assets/9d64737f-c16b-45e2-83e7-5f571617acdb)
![image](https://github.com/user-attachments/assets/e19ea326-5d7a-4e2a-bd5e-0c56362cd019)
There are people who have successfully done it and we haven't seen any similar reports yet. Are you not using sandboxed play services?

**Comment by rumpelstilz69** [comment]
I't works now, don't know why! No Goggle at all!
