### ISSUE TITLE
[Feature request]: API documentation

### ISSUE THREAD

**Issue by theimpulson** [techlore/plexus#362]
## Summary

Please provide REST API documentation to allow developers to use and integrate the API into other apps such as Aurora Store.

### Terms

- [X] This is not a duplicate of another feature request.

**Comment by theimpulson** [comment]
I can see the API endpoints on the official app [here}(https://github.com/techlore/Plexus-app/tree/main/app/src/main/java/tech/techlore/plexus/api) but having official docs for it would be more helpful.

**Comment by tomkonidas** [comment]
We will work on adding some docs for our API in the near future. It was something we had discussed in the past but never got around to adding.

**Comment by tomkonidas** [comment]
Hey @theimpulson, you can now see real-time docs via [SwaggerUI](https://plexus.techlore.tech/swaggerui), you can also run queries from there.

![image](https://github.com/user-attachments/assets/203a84b7-42ec-4068-8c47-7dd46e127450)

**Comment by theimpulson** [comment]
Thanks a lot

**Comment by theimpulson** [comment]
Hi @tomkonidas, I have been working with the API recently to add support for it in the Aurora Store. I see the API documentation doesn't mention the API endpoints to submit reviews and new apps. is that also planned? Should I reopen this issue for that open a new one?

**Comment by tomkonidas** [comment]
Hi @theimpulson we have left it out on purpose as we prefer people go through the official app to rate. The idea is the app guides the user to perform the review so it will result in cleaner data and we will also know for sure that the app was tried on the device and not just made up.

**Comment by henry-fisher** [comment]
Hey @theimpulson @tomkonidas I think there's miscommunication happening here. Following up with @tomkonidas internally to see how we can proceed here and we'll follow up!
