### ISSUE TITLE
[Feature request]: GUI support for landscape / tablet view

### ISSUE THREAD

**Issue by SomebodyYouProbablyDontKnow** [techlore/plexus#371]
### Description

Many menus, buttons, and so on are often positioned out of the screen, getting cut off or similar, which makes the app unusable on tablets or in landscape mode.

### Terms

- [X] This is not a duplicate of another feature request.

**Comment by StellarSand** [comment]
Is this for the website or the app?

**Comment by StellarSand** [comment]
Then please open the issue on the [app's repo](https://github.com/techlore/plexus-app/issues/) along with a few screenshots.
