### ISSUE TITLE
Revamp User Interface to Ditch Number System for End Users

### ISSUE THREAD

**Issue by henryistaken** [techlore/plexus#60]
Numbers are perfect for internal spread sheets and and values, but for a website it may be more intuitive to translate these to more visual queues. 

Some ideas:
Stars (1-4 stars)
Rank (Gold, silver, bronze) - Similar to ProtonDB

This would replace a generic “4” on the website, and would allow us to better award and represent things with great compatibility. Gold sounds a lot better than 4 :) 

@tomkonidas You’d probably be a good person to figure out how to make this change happen with the current site UI

**Comment by tomkonidas** [comment]
@techlore-official Thats a great idea!

Looking at ProtonDB, this would be the breakdown:

|Stars|Rank|
|---|---|
|X|Unrated|
|1|Borked|
|2|Bronze|
|3|Silver|
|4|Gold|

We could also go this route:

|Stars|Rank|
|---|---|
|X|Unrated|
|1|Bronze|
|2|Silver|
|3|Gold|
|4|Platinum or Native?|

Is there any you prefer? Mind you it is not hard to change later on.

**Comment by techlore-official** [comment]
My bad for the late response. Let’s go with the first route: 

X = Unrated
1 = Borked
2  = Bronze
3 = Silver
4 = Gold
