### ISSUE TITLE
Full App List Webpage

### ISSUE THREAD

**Issue by henry-fisher** [techlore/plexus#61]
It’d be great if we could get a view similar to the spreadsheet but on the website. 

A nice visual representation of all apps on one page including:
* App names
* Ratings
* Alphabetically sorted
* Total amount of apps tested

This could show the extensiveness of everything we’ve tested and allows users to more easily browser through the database.

**Comment by amitkshatriya01** [comment]
Is this something that we're still looking to do? I can try to implement it. New to contributing to projects so it may take some time but I can help.
