### ISSUE TITLE
Add support for app categories 

### ISSUE THREAD

**Issue by henryistaken** [techlore/plexus#62]
Not a priority currently, but down the road adding app categories won’t be very challenging and will allow users to find and categorize apps by a category. 

Ex. Users curious what games they can play on GrapheneOS can sort by “Games” on Plexus.

**Comment by techlore-official** [comment]
Update: This will only be implemented into the API - not using the CSV format to avoid complicating it further.

**Comment by henryistaken** [comment]
No longer think this is useful.
