### ISSUE TITLE
Multiple reviews per app

### ISSUE THREAD

**Issue by Productive2** [techlore/plexus#64]
This is how previous successful compatibility review systems do it (https://www.protondb.com/) and (https://appdb.winehq.org/).
Although it does indeed make the interface more complicated, and is perhaps more relevant if multiple conflicting reports arise for some applications. I just wanted to throw the idea out there for discussion.

**Comment by tomkonidas** [comment]
Multiple entries could be nice but not the way we store data now (in a csv file). It would also add another layer to the mix with having to make sure everyone uses the same app identifier. Which is not always easy to identify for everyone. For example if someone just downloads an APK from a site directly. theres no store identifier

**Comment by techlore-official** [comment]
We will be moving down this road in the future. In our current state, the CSV file is a major limitation, but one we are working with. As time continues we can expand this out and find more efficient ways of scaling this project

**Comment by techlore-official** [comment]
This is referenced in the readme in our future plans so going to be closing the issue. Thank you for the suggestion!
